exports.contact = [
  'WANT TO WORK TOGETHER?',
  'image-contact',
  'Inquiries,<br/>Feedback,<br/>Support',
  'Send me a message to get in touch. Always happy to receive info requests, hear customer feedback or provide app support!',
  'Too short',
  'Required',
  'Message could not be sent. Please try again later',
  'Thanks for your message!',
  'Name',
  'John',
  'Email Address',
  'johsmith@gmail.com',
  'Message Type',
  'Message',
  'Enter message here',
  'Sending',
  'Submit',
  'Reset'
]
