import React from 'react'
import classNames from 'classnames'
import { makeStyles } from '@material-ui/styles'
import { constants } from '@cjo3/shared/raw/constants/keyword-multiplier'
import {
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Button,
  Typography
} from '@material-ui/core'

const useStyles = makeStyles(theme => {
  const baseFont = {
    fontFamily: theme.typography.fontFamily,
    fontSize: theme.custom.setSpace() * 1.5,
    color: theme.palette.bodyColor,
    lineHeight: 1.5,
    margin: 0,
    padding: 0
  }
  return {
    mainHeading: {
      ...baseFont,
      ...theme.typography.bold,
      fontSize: theme.custom.setSpace('sm'),
      color: theme.palette.primary.main
    },
    subHeading: {
      ...baseFont
    },
    section: {
      'marginTop': theme.custom.setSpace('sm'),
      '&:first-child': {
        marginTop: theme.custom.setSpace()
      }
    },
    sectionHeading: {
      ...baseFont,
      ...theme.typography.bold,
      textTransform: 'uppercase'
    },
    copy: {
      ...baseFont,
      marginTop: theme.custom.setSpace(),
      textIndent: theme.custom.setSpace()
    },
    listItem: {
      ...baseFont
    },
    siteLink: {
      ...baseFont,
      'color': theme.palette.primary[600],
      'textDecoration': 'none',
      'transition': 'all 250ms ease-out',
      '&:hover': {
        color: theme.palette.primary[400],
        cursor: 'pointer'
      }
    },
    secionSub: {
      ...theme.custom.borderRadius,
      backgroundColor: theme.palette.grey[100],
      padding: theme.custom.setSpace()
    },
    sectionSubHeading: {
      'marginTop': theme.custom.setSpace(),
      '&:first-child': {
        marginTop: 0
      },
      'color': theme.palette.primary.main
    }
  }
})

export const PrivacyPolicy = ({
  open,
  closeHandler,
  siteName,
  siteUrl,
  siteContactEmail
}) => {
  const classes = useStyles()

  const setSiteLink = () => (
    <a
      href={siteUrl}
      _target="blank"
      rel="nofollow"
      className={classes.siteLink}>
      {siteName}
    </a>
  )
  return (
    <Dialog open={open} onClose={closeHandler} maxWidth={false}>
      <DialogTitle>
        <Typography className={classes.mainHeading}>Privacy Policy</Typography>
        <Typography className={classes.subHeading}>
          Updated on October 13th, 2020
        </Typography>
      </DialogTitle>

      <DialogContent dividers>
        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            General Terms
          </Typography>
          <Typography className={classes.copy}>
            {setSiteLink()}&nbsp;&#40;&quot;we&quot;, &quot;our&quot; or
            &quot;us&quot;&#41; is committed to protecting your privacy. This
            Privacy Policy explains how your personal information is collected,
            used, and disclosed by
          </Typography>
          <Typography className={classes.copy}>
            {setSiteLink()}&nbsp;This Privacy Policy applies to our
            website,&nbsp;
            <a href={siteUrl} className={classes.siteLink}>
              {siteUrl}
            </a>
            , and its associated subdomains &#40;collectively, our
            &quot;Service&quot;&#41;.
          </Typography>
          <Typography className={classes.copy}>
            By accessing or using our Service, you signify that you have read,
            understood, and agree to our collection, storage, use, and
            disclosure of your personal information as described in this Privacy
            Policy and our Terms of Service.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Definitions and key terms
          </Typography>
          <Typography className={classes.copy}>
            To help explain things as clearly as possible in this Privacy
            Policy, every time any of these terms are referenced, are strictly
            defined as&#58;
          </Typography>
          <ul>
            <li className={classes.listItem}>
              <strong>Cookie&#58;</strong> small amount of data generated by a
              website and saved by your web browser. It is used to identify your
              browser, provide analytics, remember information about you such as
              your language preference or login information.
            </li>
            <li className={classes.listItem}>
              <strong>Company&#58;</strong> when this policy mentions
              &quot;Company&quot;, &quot;we&quot;, &quot;us&quot;, or
              &quot;our&quot;, it refers to&nbsp;
              {setSiteLink()}
              &nbsp;that is responsible for your information under this Privacy
              Policy.
            </li>
            <li className={classes.listItem}>
              <strong>Country&#58;</strong> where&nbsp;
              {setSiteLink()}
              &nbsp;or the owners&frasl;founders of&nbsp;
              {setSiteLink()}
              &nbsp;are based, in this case is <a>Canada</a>.
            </li>
            <li className={classes.listItem}>
              <strong>Customer&#58;</strong> refers to the company, organization
              or person that signs up to use the&nbsp;
              {setSiteLink()}
              &nbsp;Service to manage the relationships with your consumers or
              service users.
            </li>
            <li className={classes.listItem}>
              <strong>Device&#58;</strong> any internet connected device such as
              a phone, tablet, computer or any other device that can be used to
              visit&nbsp;
              {setSiteLink()}
              &nbsp;and use the services.
            </li>
            <li className={classes.listItem}>
              <strong>IP address&#58;</strong> Every device connected to the
              Internet is assigned a number known as an Internet protocol
              &#40;IP&#41; address. These numbers are usually assigned in
              geographic blocks. An IP address can often be used to identify the
              location from which a device is connecting to the Internet.
            </li>
            <li className={classes.listItem}>
              <strong>Personnel&#58;</strong> refers to those individuals who
              are employed by&nbsp;
              {setSiteLink()}
              &nbsp;or are under contract to perform a service on behalf of one
              of the Parties.
            </li>
            <li className={classes.listItem}>
              <strong>Personal Data&#58;</strong> any information that directly,
              indirectly, or in connection with other
              information&mdash;including a personal identification
              number&mdash;allows for the identification or identifiability of a
              natural person.
            </li>
            <li className={classes.listItem}>
              <strong>Service&#58;</strong> refers to the service provided
              by&nbsp;
              {setSiteLink()}
              &nbsp;as described in the relative terms &#40;if available&#41;
              and on this platform.
            </li>
            <li className={classes.listItem}>
              <strong>Third&ndash;Party Service&#58;</strong> refers to
              advertisers, contest sponsors, promotional and marketing partners,
              and others who provide our content or whose products or services
              we think may interest you.
            </li>
            <li className={classes.listItem}>
              <strong>Website&#58;</strong>&nbsp;{setSiteLink()}&apos;s site,
              which can be accessed via this URL&#58;&nbsp;
              <a href={siteUrl} className={classes.siteLink}>
                {siteUrl}
              </a>
            </li>
            <li className={classes.listItem}>
              <strong>You&#58;</strong> a person or entity that is registered
              with&nbsp;
              {setSiteLink()}
              &nbsp;to use the Services.
            </li>
          </ul>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            What Information Do We Collect?
          </Typography>
          <Typography className={classes.copy}>
            We collect information from you when you visit our service,
            register, place an order, subscribe to our newsletter, respond to a
            survey or fill out a form.
          </Typography>
          <ul>
            <li className={classes.copy}>IP address</li>
            <li className={classes.copy}>Order details</li>
            <li className={classes.copy}>Email address, if submitted</li>
          </ul>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            How Do We Use The Information We Collect?
          </Typography>
          <Typography className={classes.copy}>
            Any of the information we collect from you may be used in one of the
            following ways&#58;
          </Typography>
          <ul>
            <li className={classes.copy}>
              To personalize your experience &#40;your information helps us to
              better respond to your individual needs&#41;
            </li>
            <li className={classes.copy}>
              To improve our service &#40;we continually strive to improve our
              service offerings based on the information and feedback we receive
              from you&#41;
            </li>
            <li className={classes.copy}>To process transactions</li>
            <li className={classes.copy}>
              To administer a contest, promotion, survey or other site feature
            </li>
            <li className={classes.copy}>To send periodic emails</li>
          </ul>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            When do we use customer information from Third&ndash;Parties?
          </Typography>
          <Typography className={classes.copy}>
            We receive some information from the Third&ndash;Parties when you
            contact us. For example, when you submit your email address to us to
            show interest in becoming our customer, we receive information from
            a Third-Party that provides automated fraud detection services to
            us. We also occasionally collect information that is made publicly
            available on social media websites. You can control how much of your
            information social media websites make public by visiting these
            websites and changing your privacy settings.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Do we share the information we collect with Third&ndash;Parties?
          </Typography>
          <Typography className={classes.copy}>
            We may share the information that we collect, both personal and
            non&ndash;personal, with Third&ndash;Parties such as advertisers,
            contest sponsors, promotional and marketing partners, and others who
            provide our content or whose products or services we think may
            interest you. We may also share it with our current and future
            affiliated companies and business partners, and if we are involved
            in a merger, asset sale or other business reorganization, we may
            also share or transfer your personal and non&ndash;personal
            information to our successors&ndash;in&ndash;interest.
          </Typography>
          <Typography className={classes.copy}>
            We may share portions of our log file data, including IP addresses,
            for analytics purposes with Third&ndash;Parties such as web
            analytics partners, application developers, and ad networks. If your
            IP address is shared, it may be used to estimate general location
            and other technographics such as connection speed, whether you have
            visited the service in a shared location, and type of device used to
            visit the service. They may aggregate information about our
            advertising and what you see on the service and then provide
            auditing, research and reporting for us and our advertisers.
          </Typography>
          <Typography className={classes.copy}>
            We may also disclose personal and non&ndash;personal information
            about you to government or law enforcement officials or private
            Parties as we, in our sole discretion, believe necessary or
            appropriate in order to respond to claims, legal process
            &#40;including subpoenas&#41;, to protect our rights and interests
            or those of a Third-Party, the safety of the public or any person,
            to prevent or stop any illegal, unethical, or legally actionable
            activity, or to otherwise comply with applicable court orders, laws,
            rules and regulations.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Where and when is information collected from customers and end
            users?
          </Typography>
          <Typography className={classes.copy}>
            We will collect personal information that you submit to us. We may
            also receive personal information about you from Third&ndash;Parties
            as described above.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Could my information be transferred to other countries?
          </Typography>
          <Typography className={classes.copy}>
            We are incorporated in Canada. Information collected via our
            website, through direct interactions with you, or from use of our
            help services may be transferred from time to time to our offices or
            personnel, or to Third&ndash;Parties, located throughout the world,
            and may be viewed and hosted anywhere in the world, including
            countries that may not have laws of general applicability regulating
            the use and transfer of such data. To the fullest extent allowed by
            applicable law, by using any of the above, you voluntarily consent
            to the trans-border transfer and hosting of such information.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Is the information collected through our service secure?
          </Typography>
          <Typography className={classes.copy}>
            We take precautions to protect the security of your information. We
            have physical, electronic, and managerial procedures to help
            safeguard, prevent unauthorized access, maintain data security, and
            correctly use your information. However, neither people nor security
            systems are foolproof, including encryption systems. In addition,
            people can commit intentional crimes, make mistakes or fail to
            follow policies. Therefore, while we use reasonable efforts to
            protect your personal information, we cannot guarantee its absolute
            security. If applicable law imposes any non-disclaimable duty to
            protect your personal information, you agree that intentional
            misconduct will be the standards used to measure our compliance with
            that duty.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Can I update or correct my information?
          </Typography>
          <Typography className={classes.copy}>
            The rights you have to request updates or corrections to the
            information we collect depend on your relationship with us.
            Personnel may update or correct their information as detailed in our
            internal company employment policies. Customers have the right to
            request the restriction of certain uses and disclosures of
            personally identifiable information as follows. You can contact us
            in order to (1) update or correct your personally identifiable
            information, (2) change your preferences with respect to
            communications and other information you receive from us, or (3)
            delete the personally identifiable information maintained about you
            on our systems (subject to the following paragraph), by cancelling
            your account. Such updates, corrections, changes and deletions will
            have no effect on other information that we maintain, or information
            that we have provided to Third&ndash;Parties in accordance with this
            Privacy Policy prior to such update, correction, change or deletion.
            To protect your privacy and security, we may take reasonable steps
            (such as requesting a unique password) to verify your identity
            before granting you profile access or making corrections. You are
            responsible for maintaining the secrecy of your unique password and
            account information at all times. You should be aware that it is not
            technologically possible to remove each and every record of the
            information you have provided to us from our system. The need to
            back up our systems to protect information from inadvertent loss
            means that a copy of your information may exist in a non-erasable
            form that will be difficult or impossible for us to locate. Promptly
            after receiving your request, all personal information stored in
            databases we actively use, and other readily searchable media will
            be updated, corrected, changed or deleted, as appropriate, as soon
            as and to the extent reasonably and technically practicable. If you
            are an end user and wish to update, delete, or receive any
            information we have about you, you may do so by contacting the
            organization of which you are a customer.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Sale of Business
          </Typography>
          <Typography className={classes.copy}>
            We reserve the right to transfer information to a Third-Party in the
            event of a sale, merger or other transfer of all or substantially
            all of the assets of us or any of its Corporate Affiliates (as
            defined herein), or that portion of us or any of its Corporate
            Affiliates to which the Service relates, or in the event that we
            discontinue our business or file a petition or have filed against us
            a petition in bankruptcy, reorganization or similar proceeding,
            provided that the Third-Party agrees to adhere to the terms of this
            Privacy Policy.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>Affiliates</Typography>
          <Typography className={classes.copy}>
            We may disclose information (including personal information) about
            you to our Corporate Affiliates. For purposes of this Privacy
            Policy, &quot;Corporate Affiliate&quot; means any person or entity
            which directly or indirectly controls, is controlled by or is under
            common control with us, whether by ownership or otherwise. Any
            information relating to you that we provide to our Corporate
            Affiliates will be treated by those Corporate Affiliates in
            accordance with the terms of this Privacy Policy.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            How Long Do We Keep Your Information?
          </Typography>
          <Typography className={classes.copy}>
            We keep your information only so long as we need it to provide
            service to you and fulfill the purposes described in this policy.
            This is also the case for anyone that we share your information with
            and who carries out services on our behalf. When we no longer need
            to use your information and there is no need for us to keep it to
            comply with our legal or regulatory obligations, we&apos;ll either
            remove it from our systems or depersonalize it so that we can&apos;t
            identify you.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            How Do We Protect Your Information?
          </Typography>
          <Typography className={classes.copy}>
            We implement a variety of security measures to maintain the safety
            of your personal information when you place an order or enter,
            submit, or access your personal information. We offer the use of a
            secure server. All supplied sensitive&frasl;credit information is
            transmitted via Secure Socket Layer &#40;SSL&#41; technology and
            then encrypted into our Payment gateway providers database only to
            be accessible by those authorized with special access rights to such
            systems, and are required to keep the information confidential.
            After a transaction, your private information (credit cards, social
            security numbers, financials, etc.) is never kept on file. We
            cannot, however, ensure or warrant the absolute security of any
            information you transmit to us or guarantee that your information on
            the Service may not be accessed, disclosed, altered, or destroyed by
            a breach of any of our physical, technical, or managerial
            safeguards.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Governing Law
          </Typography>
          <Typography className={classes.copy}>
            The laws of Canada, excluding its conflicts of law rules, shall
            govern this Agreement and your use of our service. Your use of our
            service may also be subject to other local, state, national, or
            international laws.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Your Consent
          </Typography>
          <Typography className={classes.copy}>
            By using our service, registering an account, or making a purchase,
            you consent to this Privacy Policy.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Links to Other Websites
          </Typography>
          <Typography className={classes.copy}>
            This Privacy Policy applies only to the Services. The Services may
            contain links to other websites not operated or controlled by us. We
            are not responsible for the content, accuracy or opinions expressed
            in such websites, and such websites are not investigated, monitored
            or checked for accuracy or completeness by us. Please remember that
            when you use a link to go from the Services to another website, our
            Privacy Policy is no longer in effect. Your browsing and interaction
            on any other website, including those that have a link on our
            platform, is subject to that website’s own rules and policies. Such
            Third&ndash;Parties may use their own cookies or other methods to
            collect information about you.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>Cookies</Typography>
          <Typography className={classes.copy}>
            We use &quot;Cookies&quot; to identify the areas of our website that
            you have visited. A Cookie is a small piece of data stored on your
            computer or mobile device by your web browser. We use Cookies to
            personalize the Content that you see on our website. Most web
            browsers can be set to disable the use of Cookies. However, if you
            disable Cookies, you may not be able to access functionality on our
            website correctly or at all. We never place Personally Identifiable
            Information in Cookies.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Payment Details
          </Typography>
          <Typography className={classes.copy}>
            We do not collect, store or keep any confidential credit card
            information or payment details. Payments are handled by&nbsp;
            <a href={constants.URLS.STRIPE} className={classes.siteLink}>
              Stripe
            </a>
            .
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Kids&apos; Privacy
          </Typography>
          <Typography className={classes.copy}>
            We collect information from kids under the age of 13 just to better
            our services. If You are a parent or guardian and You are aware that
            Your child has provided Us with Personal Data without your
            permission, please contact Us. If We become aware that We have
            collected Personal Data from anyone under the age of 13 without
            verification of parental consent, We take steps to remove that
            information from our servers.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Changes To Our Privacy Policy
          </Typography>
          <Typography className={classes.copy}>
            If we decide to change our privacy policy, we will post those
            changes on this page, and&frasl;or update the Privacy Policy
            modification date below.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>
            Third&ndash;Party Services
          </Typography>
          <Typography className={classes.copy}>
            We may display, include or make available Third&ndash;Party content
            (including data, information, applications and other products
            services) or provide links to Third&ndash;Party websites or services
            (&quot;Third&ndash;Party Services&quot;).
          </Typography>
          <Typography className={classes.copy}>
            You acknowledge and agree that we shall not be responsible for any
            Third&ndash;Party Services, including their accuracy, completeness,
            timeliness, validity, copyright compliance, legality, decency,
            quality or any other aspect thereof. We do not assume and shall not
            have any liability or responsibility to you or any other person or
            entity for any Third&ndash;Party Services.
          </Typography>
          <Typography className={classes.copy}>
            Third&ndash;Party Services and links thereto are provided solely as
            a convenience to you and you access and use them entirely at your
            own risk and subject to such Third&ndash;Parties&apos; terms and
            conditions.
          </Typography>
        </section>

        <section className={classNames(classes.section, classes.secionSub)}>
          <Typography
            className={classNames(
              classes.sectionHeading,
              classes.sectionSubHeading
            )}>
            Information about General Data Protection Regulation &#40;GDPR&#41;
          </Typography>
          <Typography className={classes.copy}>
            We may be collecting and using information from you if you are from
            the European Economic Area &#40;EEA&#41;, and in this section of our
            Privacy Policy we are going to explain exactly how and why is this
            data collected, and how we maintain this data under protection from
            being replicated or used in the wrong way.
          </Typography>
          <Typography
            className={classNames(
              classes.sectionHeading,
              classes.sectionSubHeading
            )}>
            What is GDPR?
          </Typography>
          <Typography className={classes.copy}>
            GDPR is an EU&ndash;wide privacy and data protection law that
            regulates how EU residents&apos; data is protected by companies and
            enhances the control the EU residents have, over their personal
            data.
          </Typography>
          <Typography
            className={classNames(
              classes.sectionHeading,
              classes.sectionSubHeading
            )}>
            What is personal data?
          </Typography>
          <Typography className={classes.copy}>
            Any data that relates to an identifiable or identified individual.
            GDPR covers a broad spectrum of information that could be used on
            its own, or in combination with other pieces of information, to
            identify a person. Personal data extends beyond a person’s name or
            email address. Some examples include financial information,
            political opinions, genetic data, biometric data, IP addresses,
            physical address, sexual orientation, and ethnicity. The Data
            Protection Principles include requirements such as&#58;
          </Typography>
          <ul>
            <li className={classes.copy}>
              Personal data collected must be processed in a fair, legal, and
              transparent way and should only be used in a way that a person
              would reasonably expect.
            </li>
            <li className={classes.copy}>
              Personal data should only be collected to fulfil a specific
              purpose and it should only be used for that purpose. Organizations
              must specify why they need the personal data when they collect it.
            </li>
            <li className={classes.copy}>
              Personal data should be held no longer than necessary to fulfil
              its purpose.
            </li>
            <li className={classes.copy}>
              People covered by the GDPR have the right to access their own
              personal data. They can also request a copy of their data, and
              that their data be updated, deleted, restricted, or moved to
              another organization.
            </li>
          </ul>
          <Typography
            className={classNames(
              classes.sectionHeading,
              classes.sectionSubHeading
            )}>
            Why is GDPR important?
          </Typography>
          <Typography className={classes.copy}>
            GDPR adds some new requirements regarding how companies should
            protect individuals&apos; personal data that they collect and
            process. It also raises the stakes for compliance by increasing
            enforcement and imposing greater fines for breach. Beyond these
            facts it&apos;s simply the right thing to do. At Help Scout we
            strongly believe that your data privacy is very important and we
            already have solid security and privacy practices in place that go
            beyond the requirements of this new regulation.
          </Typography>
          <Typography
            className={classNames(
              classes.sectionHeading,
              classes.sectionSubHeading
            )}>
            Individual Data Subject&apos;s Rights &ndash; Data Access,
            Portability and Deletion
          </Typography>
          <Typography className={classes.copy}>
            We are committed to helping our customers meet the data subject
            rights requirements of GDPR. processes or stores all personal data
            in fully vetted, DPA compliant vendors. We do store all conversation
            and personal data for up to 6 years unless your account is deleted.
            In which case, we dispose of all data in accordance with our Terms
            of Service and Privacy Policy, but we will not hold it longer than
            60 days.
          </Typography>
          <Typography className={classes.copy}>
            We are aware that if you are working with EU customers, you need to
            be able to provide them with the ability to access, update, retrieve
            and remove personal data. We got you! We&apos;ve been set up as self
            service from the start and have always given you access to your data
            and your customers data. Our customer support team is here for you
            to answer any questions you might have about working with the API.
          </Typography>
        </section>

        <section className={classNames(classes.section, classes.secionSub)}>
          <Typography
            className={classNames(
              classes.sectionHeading,
              classes.sectionSubHeading
            )}>
            California Residents
          </Typography>
          <Typography className={classes.copy}>
            The California Consumer Privacy Act &#40;CCPA&#41; requires us to
            disclose categories of Personal Information we collect and how we
            use it, the categories of sources from whom we collect Personal
            Information, and the Third&ndash;Parties with whom we share it,
            which we have explained above.
          </Typography>
          <Typography className={classes.copy}>
            We are also required to communicate information about rights
            California residents have under California law. You may exercise the
            following rights&#58;
          </Typography>
          <ul>
            <li className={classes.copy}>
              Right to Know and Access. You may submit a verifiable request for
              information regarding the&#58; &#40;1&#41; categories of Personal
              Information we collect, use, or share; &#40;2&#41; purposes for
              which categories of Personal Information are collected or used by
              us; &#40;3&#41; categories of sources from which we collect
              Personal Information; and &#40;4&#41; specific pieces of Personal
              Information we have collected about you.
            </li>
            <li className={classes.copy}>
              Right to Equal Service. We will not discriminate against you if
              you exercise your privacy rights.
            </li>
            <li className={classes.copy}>
              Right to Delete. You may submit a verifiable request to close your
              account and we will delete Personal Information about you that we
              have collected.
            </li>
            <li className={classes.copy}>
              Request that a business that sells a consumer&apos;s personal
              data, not sell the consumer&apos;s personal data.
            </li>
          </ul>
          <Typography className={classes.copy}>
            If you make a request, we have one month to respond to you. If you
            would like to exercise any of these rights, please contact us.
          </Typography>
          <Typography className={classes.copy}>
            We do not sell the Personal Information of our users.
          </Typography>
          <Typography className={classes.copy}>
            For more information about these rights, please contact us.
          </Typography>
        </section>

        <section className={classNames(classes.section, classes.secionSub)}>
          <Typography
            className={classNames(
              classes.sectionHeading,
              classes.sectionSubHeading
            )}>
            California Online Privacy Protection Act &#40;CalOPPA&#41;
          </Typography>
          <Typography className={classes.copy}>
            CalOPPA requires us to disclose categories of Personal Information
            we collect and how we use it, the categories of sources from whom we
            collect Personal Information, and the Third&ndash;Parties with whom
            we share it, which we have explained above.
          </Typography>
          <Typography className={classes.copy}>
            CalOPPA users have the following rights&#58;
          </Typography>
          <ul>
            <li className={classes.copy}>
              Right to Know and Access. You may submit a verifiable request for
              information regarding the&#58; &#40;1&#41; categories of Personal
              Information we collect, use, or share; &#40;2&#41; purposes for
              which categories of Personal Information are collected or used by
              us; &#40;3&#41; categories of sources from which we collect
              Personal Information; and &#40;4&#41; specific pieces of Personal
              Information we have collected about you.
            </li>
            <li className={classes.copy}>
              Right to Equal Service. We will not discriminate against you if
              you exercise your privacy rights.
            </li>
            <li className={classes.copy}>
              Right to Delete. You may submit a verifiable request to close your
              account and we will delete Personal Information about you that we
              have collected.
            </li>
            <li className={classes.copy}>
              Right to request that a business that sells a consumer&apos;s
              personal data, not sell the consumer&apos;s personal data.
            </li>
          </ul>
          <Typography className={classes.copy}>
            If you make a request, we have one month to respond to you. If you
            would like to exercise any of these rights, please contact us.
          </Typography>
          <Typography className={classes.copy}>
            We do not sell the Personal Information of our users.
          </Typography>
          <Typography className={classes.copy}>
            For more information about these rights, please contact us.
          </Typography>
        </section>

        <section className={classes.section}>
          <Typography className={classes.sectionHeading}>Contact Us</Typography>
          <Typography className={classes.copy}>
            Don&apos;t hesitate to contact us if you have any questions.
          </Typography>
          <ul>
            <li className={classes.listItem}>
              <strong>Via Email&#58;</strong>
              &nbsp;{siteContactEmail}
            </li>
          </ul>
        </section>
      </DialogContent>
      <DialogActions>
        <Button autoFocus onClick={closeHandler} color="primary">
          Close
        </Button>
      </DialogActions>
    </Dialog>
  )
}
